export const listColors = [
  { name: 'Rojo', color: '#ff0000' },
  { name: 'Negro', color: '#000000' },
  { name: 'Amarillo', color: '#ffe100' },
  { name: 'Azul', color: '#0000ff' },
  { name: 'Verde', color: '#00ff00' },
  { name: 'Blanco', color: '#ffffff' },
  { name: 'Gris', color: '#808080' },
  { name: 'Naranja', color: '#ff7f00' },
  { name: 'Morado', color: '#800080' },
  { name: 'Rosa', color: '#ff69b4' },
  { name: 'Marrón', color: '#964b00' },
  { name: 'Azul claro', color: '#add8e6' },
  { name: 'Verde claro', color: '#90ee90' },
  { name: 'Amarillo claro', color: '#ffffe0' },
  { name: 'Naranja claro', color: '#ffa500' },
  { name: 'Rosado', color: '#ffc0cb' },
  { name: 'Turquesa', color: '#40e0d0' },
  { name: 'Lila', color: '#c8a2c8' },
  { name: 'Verde oliva', color: '#808000' },
  { name: 'Amarillo limón', color: '#f5d033' },
  { name: 'Celeste', color: '#b0e0e6' },
  { name: 'Aguamarina', color: '#7fffd4' },
  { name: 'Beige', color: '#f5f5dc' },
  { name: 'Cian', color: '#00ffff' },
  { name: 'Violeta', color: '#8a2be2' },
  { name: 'Turquesa oscuro', color: '#00ced1' },
  { name: 'Fucsia', color: '#ff00ff' },
  { name: 'Melocotón', color: '#ffdab9' },
  { name: 'Índigo', color: '#4b0082' },
  { name: 'Plata', color: '#c0c0c0' },
  { name: 'Oro', color: '#ffd700' },
  { name: 'lol', color: '#4b0022' },
  { name: 'lol', color: '#422022' },
  { name: 'lol', color: '#4f5a22' },
  { name: 'lol', color: '#4b0092' },
  { name: 'sia', color: '#c0c0c4' },
  { name: 'fasdj', color: '#ffd720' }
]
