export const options = [
	{ name: 'Ayuda/Salud y seguridad', path: '/health-security' },
	{ name: 'line', path: '' },
	{ name: 'Modo avión', path: '/airplane-mode' },
	{ name: 'Brillo de la pantalla', path: '/screen-brightness' },
	{ name: 'Audio a través de Bluetooth', path: '/bluetooth' },
	{ name: 'Bloquear pantalla', path: '/lock-screen' },
	{ name: 'line', path: '' },
	{ name: 'Control parental', path: '/parental-control' },
	{ name: 'Internet', path: '/internet' },
	{ name: 'Gestión de datos', path: '/data-management' },
	{ name: 'Usuarios', path: '/setting-user' },
	{ name: 'Mii', path: '/mii' },
	{ name: 'amiibo', path: '/amiibo' },
	{ name: 'line', path: '' },
	{ name: 'Temas', path: '/theme' },
	{ name: 'Notificaciones', path: '/notifications' },
	{ name: 'Modo de espera', path: '/standby-mode' },
	{ name: 'line', path: '' },
	{ name: 'Controles y sensores', path: '/controls-sensors' },
	{ name: 'Ajustes de TV', path: '/tv-settings' },
	{ name: 'Consola', path: '/system' },
]
